---
on:
  pull_request:
    branches:
      - main
name: Test
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        go: [ '1.17', '1.18', '1.19' ]
    name: Test on go ${{ matrix.go }} and ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ matrix.go }}
      - run: go test